[package]
name = "forkyard-api-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
alloy-consensus = { version = "=2.3.0", features = ["k256"] }
alloy-eips = "=2.3.0"
alloy-primitives = "1.6.1"
axum = "0.8.9"
eyre = "0.6.14"
forkyard-engine = { version = "0.1.0", path = "../engine" }
forkyard-fetch = { version = "0.1.0", path = "../fetch" }
revm = "41.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
alloy-consensus = "=2.3.0"
alloy-network = "=2.3.0"
alloy-primitives = "1.6.1"
alloy-provider = { version = "=2.3.0", features = ["reqwest"] }
alloy-signer-local = "=2.3.0"
dotenvy = "0.15.7"
forkyard-fetch = { path = "../fetch" }
